sudo: false
language: perl
perl:
  - '5.20'
  - '5.10'
branches:
  only:
    - master
env:
  global:
    - AUTHOR_TESTING=0
    - secure: aCvhgrduoWshWIpQq5qkPzvcREqeiFXCdYv0e/PH8FT11S2kLI1D9zpsOGRlmPcI5uchsIdgVCGqm+D7N8yR9kIA1Wgdfm40CR8EHViZ8jOMLqjV3IMvbv9JlBCUqzP2YHOTGWtQr8cQ+fv+CYZbiB0r3dH6GZYqJ38HaKTaLPY=
before_install:
  - cpanm -n Devel::Cover
script: perl Build.PL && ./Build && ./Build testcover
